### ISSUE TITLE
Social Media Name For Reporter Name Field

### ISSUE THREAD

**Issue by DShokes** [Esri/crowdsource-reporter#113]
I setup Facebook and Google+ Sign-ins. The user gets recorded by long strings like a693lED4bsKC-KQZ9gGazab_AIz in Facebook and 114457552022802211327 for Google+. These aren't very useful when displaying creators/editors in popups/other maps. Is it possible to record the user's name when they use a social media login?

**Comment by allisonmuise** [comment]
@DShokes : The user ID values are used only for identifying issues submitted by a single social media account so that reporters can review all their submitted issues. If you don't want those values to display, you can turn the user id field off in the map popup settings.

If you'd like to display a name for each reporter, I suggest exposing another text field in the map popup for that purpose. You can require people to include a name by setting the field to not accept null values.

**Comment by DShokes** [comment]
Thanks for the response Allison. In my upcoming event, 25 volunteers will be creating about 50 features each. I wouldn't expect them to type their name each time, but it would be nice to see the user's full name when reviewing data in the crowdsource manager. During reporter configuration, the parameter is called "Reporter Name Field ". A unique userID is probably not what the author is expecting. Perhaps 2 parameter fields for reporter display name and unique ID is possible?

**Comment by allisonmuise** [comment]
That's a good point - I can see how it would be confusing. I'll update the parameter name with the next release, and we'll look into adding the ability to auto-populate a name field as well. I'll create separate issues for these suggestions.
Thanks for the feedback!

**Comment by allisonmuise** [comment]
#114 #115
