### ISSUE TITLE
Issue list slow to update when changing layers

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#116]
The issues list is slow to update when changing layers. After clicking a new layer the issue list of the previous layer displays for half a second before updating to show the current layers issues.

The issues of the previous layer should not be visible during this transition

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are investigating a solution for this behavior. We will post an update soon.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
This was happening because the issue list was not cleared immediately upon changing a layer. 

We can fix this by clearing it immediately after switching a layer. So when user changes a layer, he will see an empty details panel with a loading indicator in title bar, till the issues are loaded and show up in the list.

**Comment by allisonmuise** [comment]
This will be better. Thanks!

**Comment by allisonmuise** [comment]
verified
