### ISSUE TITLE
Layers From Map Notes causing reporter to hang while loading.

### ISSUE THREAD

**Issue by DShokes** [Esri/crowdsource-reporter#118]
I converted the recreation map notes (which includes a point, line, and polygon layers) to a hosted feature service. These layers were added to a web map that worked with reporter previously. I  noticed that the layers had image popup media that referenced the IMAGE_URL field. 
I removed the media from the popups in all the layers converted from map notes and then saved the layers within map viewer. After this, crowdsource reporter loaded properly. I'm not sure whether removing the popup media or the act of updating the feature layers fixed the problem, but I figured I'd put it on your radar.

**Comment by allisonmuise** [comment]
@DShokes : Can you share the URL to the recreation map notes layer you were using when you found this?

**Comment by DShokes** [comment]
Here it is. http://arcg.is/1Mnlvoo

**Comment by allisonmuise** [comment]
@DShokes : I'm can't seem to reproduce your issue. Map notes layers shouldn't display in Reporter because they are graphics layer. Reporter will only display editable feature layers with popups. I can successfully add the layer you sent me above to a map, and it will display in the app. I also tried to reproduce the steps you are describing above, but I got different behavior.

Here's what I did to try to reproduce your steps:
1) Opened a new web map
2) Added a Map Notes layer from the Add menu and used the Recreation template
3) Saved the map and shared it with a group that feeds a test Reporter app I have configured. As expected, the map notes layer is not available in the Reporter app
4) In the Contents panel in the map, I opened the layer menu for the Map Notes layer and clicked Save Layer to create a feature layer.
5) I added the new feature layer to the map, and saved the map. This layer also doesn't display in Reporter because it doesn't have popups.
6) I added the layer you sent me to the map using Add>Add Layer From Web and saved the map. This layer appears in Reporter without issue as it has both popups and is editable.

At no point did Reporter fail to load or otherwise perform strangely. Can you provide detailed steps to reproduce Reporter hanging?

**Comment by DShokes** [comment]
1. Add Recreation Map Notes to new map
2. Save map notes as an item.
3. Click publish in the item detail page to create a new service.
![1 - feature collection](https://cloud.githubusercontent.com/assets/3903212/9234404/4b63b9b2-40fe-11e5-8a41-33064ee48098.jpg)

4. Enable editing, export, sync, and edit tracking. Then update sharing.
5. Add to new map.
![2 - feature layers](https://cloud.githubusercontent.com/assets/3903212/9234466/93b21b5a-40fe-11e5-867c-42cd00155f11.jpg)
6. View unaltered popup.
![3 - popup media](https://cloud.githubusercontent.com/assets/3903212/9234481/a5395172-40fe-11e5-948e-4e8c529156b8.jpg)

7. Here is the reporter before adding the new layers to the web map.
![4 - before adding layers](https://cloud.githubusercontent.com/assets/3903212/9234502/ca2f2f10-40fe-11e5-96c7-ba9552f31a4a.jpg)

8. Add feature service layers derived from map notes to the web map. Save.
![5 - added layers to web map](https://cloud.githubusercontent.com/assets/3903212/9234512/e1bc0284-40fe-11e5-81ed-a1b957dd887c.jpg)

9, Refresh reporter and it fails after sign in.
![6 - refreshed reported](https://cloud.githubusercontent.com/assets/3903212/9234526/fafc2eae-40fe-11e5-8eb6-a7ed97ae58fd.jpg)
