### ISSUE TITLE
Message when signing in to facebook

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#123]
When singing in to an app via Facebook with the account that registered the connection between the app and FB, the following appears in the FB window:
![8-24-2015 4-55-58 pm](https://cloud.githubusercontent.com/assets/2752195/9455549/3f0c1362-4a81-11e5-9b3e-2d067137f25f.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise

We are investigating this behavior. We will post an update soon

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We investigated and found that this message is displayed only to the user whose credentials are used to configure the Facebook login. It is not displayed to public users who log in with their Facebook accounts.

We also confirmed that we are using Facebook's JavaScript SDK and we have not specified an explicit display type or height/width. 

We see that the message is displayed only when you maximize (to larger than 400x580px) the Facebook login window. Can you please confirm this.

If you are seeing the message only when the window is resized to larger dimensions, then it is expected behavior to show the warning message. This message is displayed only to FB auth user.

**Comment by allisonmuise** [comment]
@CTLocalGov

This is correct. I am only seeing it under those circumstances. I will close this issue as you state that we are following the suggested practices.
