### ISSUE TITLE
Set max search distance

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#136]
The app spins indefinitely looking for features that are 1000s of miles away when location is enabled.

For each 'View More' click, expand the search area a maximum of 10 times searching for the nearest feature. If there are still no features found, display the same message and 'View More' button.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Agree. We will expand the search area a maximum of 10 times and display "View More" if there are still no features found. We will include this in the next code drop.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
The app still seems to be expanding the search area further than I expect. The search radius in my app is 3 miles, and I've given the app access to my location. As expected, the map shows the area around my location when it loads. When I click 'view more' it very quickly zooms all the way out to a global scale. Based on our discussion above, I would only expect to see 30 miles. Can you provide any information on what is happening?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We are unable to reproduce this. Ideally, the app should stop at 13 miles (3 miles on initial load and increment by 1 mile for 10 times) and display the view more button.

Can you please share a link to the app and also the current location (lat,long) you are using.

**Comment by allisonmuise** [comment]
This is not correct. Per earlier conversations, the search buffer should expand by the configured amount, not 1 unit.

When the configured search distance is 3 miles, the app should be searching for reports within 3 miles of my current location on load. It should then expand the search distance to 6 miles (2 x 3 miles) when the 'view more' button is pressed. If no features are found within 6 miles, it should automatically expand to 9 (3x), 12 (4x), 15 (5x)...miles until a feature is found - to a maximum of 30 (3 x 10) miles.

Here is an example of this issue:
http://localgovtestdev.mapsdevext.arcgis.com/apps/CrowdsourceReporter/index.html?appid=990ff8e3776a454599d4fd29a1da6ca4
The app is public, but you will need the username and password sent previously to get past the devext shield page.

My current location is 34.0579, -117.171

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
I think we misinterpreted the statement *"The buffer distance should increment, not double, when clicking 'view more'."* as mentioned in [this issue](https://github.com/Esri/crowdsource-reporter/issues/62#issuecomment-86603004)

This is a minor fix to change the current `buffer distance + 1 mile` to `bufferdistance + bufferdistance` when view more is clicked.

We also found the root cause of zooming out to global scale. This was due to the buffer distance parameter being set as a string. As a consequence initial 3 miles was changing to 31 miles and then 311 miles and 3111 miles and so on. 

This is also a minor fix. We'll have to change this to a number parameter as shown in the screenshot from docs below. 
Please suggest valid values for the `"constraints" :{min:0,max:10,places:0}` you'd like to set.

![image](https://cloud.githubusercontent.com/assets/2959186/10476734/1a7d1d7e-726e-11e5-8956-da8db94b7166.png)

**Comment by allisonmuise** [comment]
per this morning's call these constraints are optional, therefore we will not constrain the values users can provide for the buffer distance.

**Comment by allisonmuise** [comment]
verified
