### ISSUE TITLE
default date in comment form

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#142]
like with the main geoform, date fields in the comment form should use the default value set in the dataset if available, otherwise they should default to today's date. If the field contains a range domain that does not include today's date, use the min date accepted by the field.

**Comment by allisonmuise** [comment]
(currently, if a date field has a set range domain that does not include the Dec 29, 1899, the app accepts the 1899 value even though it is outside the domain, instead of requiring a valid value. setting the default to something inside the domain if one is present will resolve this.)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

When a default date is provided in the related table for a field, then the feature service displays incorrect value. This looks like a bug in ArcGIS Server and ArcGIS Online hosted services too. 

ArcGIS REST API always represents date values in milliseconds since epoch (1/1/1970 00:00:00). When a range domain is applied to a date field, you can observe that the range bounds are in milliseconds since epoch. This is correct.

However, when a default date value is applied to a field in related tables, it displays number of days since 1/1/1900 (just as in MS Excel) in the feature service instead of milliseconds since epoch.

Please see the highlighted portions of this screenshot describing the table properties in JSON for this [feature service](http://services1.arcgis.com/DlnuvLGpDczjeSgG/ArcGIS/rest/services/points_reporter/FeatureServer/1)

![image](https://cloud.githubusercontent.com/assets/2959186/12020689/2657214a-ada5-11e5-9a40-7a88da59cbaa.png)

This is the reason that the app is reading it as milliseconds since epoch and displaying the default date value that is outside the range. Default date values when set in a feature layer works correctly, i.e., they show up in milliseconds since epoch. Its only for the tables where this doesn't work.

To work around this issue, we plan  to introduce a check to see if the default date is between the range bounds and if not, display the min date value as default in the app.

Please let us know if this is ok.

**Comment by allisonmuise** [comment]
Yes, this is ok. I will also let the AGOL team know about the discrepancy in how dates are being stored.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : After playing around with range domains and default date values in AGOL, I think I've figured this out - at least I am now able to get the correct default value in the comment form. The values that are stored seem to be related to how the date field is set up. If time is enabled, the millisecond value seems to be stored. If it is not, the days values seems to be stored. No changes are needed to how the app is handling these values. I will close this issue.
