### ISSUE TITLE
application hangs under specific circumstances

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#151]
Repro steps:
1. Open a layer in Reporter
2. Submit a new report outside the initial extents of the map (current extent of the map doesn't matter)
3. Return to the feature list
4. Note that the new feature is included in the list and there is no Load More button
5. Open another layer from the same map, then return to the layer with the new feature. (layer from different map does not trigger the same behavior)
6. Note that the feature list now has a 'Load More' button, and the new feature is not listed.
7. Click the Load More button and the app will hang.
8. Refresh the app, return to the layer, and all features (including the new one) appear in the list

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We were able to reproduce the issue. 
The issue is occurring because one of the queries when a layer is loaded again (to get features) was being picked from browser cache. Due to this, there is a mismatch in the number of features that the layer has and what the app thinks the layer has. This is also the reason why you see the ‘View More’ button and the app breaks when you click it. 

We are able to fix this in the app by avoiding the usage of cache in such cases by adding a random element (timestamp) in the query so that it is unique every time. 

We are testing this today and will be able to send a pull request tomorrow.

**Comment by allisonmuise** [comment]
Thank you!

**Comment by allisonmuise** [comment]
verified
