### ISSUE TITLE
Store Location Information on Features

### ISSUE THREAD

**Issue by ScottOppmann** [Esri/crowdsource-reporter#162]
Add configurable option to the Crowdsource Reporter application that allows users to store address or location information entered in search box on map control (using locator).  The field should be consistent across features and configurable when authoring the app (much like votes). Providing this option will allow users to persist descriptive location information (address, intersection, place name) on each feature and removes any redundant data entry currently needed to do this in the form currently.

Note:  Must determine how to handle map clicks and current location function.  Perhaps the best approach is to not store anything when a user uses one of these methods to create a feature on map.  

@allisonmuise - please review this issue, add any detail you deem necessary, and work with @CTLocalGovTeam to include it in the 4.2 release.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Here's our understanding of this feature. Can you please confirm.
1. Add a configuration option to select field to store location
2. This field will be assumed available in all layers, similar to Votes field. 
3. If field is not present in any layer, then this feature will not be triggered for that layer
4. The location field should be of string data type. For location field other than string type, feature will not be triggered.
5. The location field will be auto-populated when user adds a point by searching an address
6. Both search boxes (main map and geoform map) will trigger this feature of auto-populating location field in report form
7. If user adds a point by searching an address and later clicks on the map to re-locate the point, the location field will be cleared
8. If user adds a point by clicking on map, or using geolocation button, the location field will not be auto-populated 
9. This feature of auto-populating location information will not be triggered for line and polygon layers

**Comment by allisonmuise** [comment]
@ScottOppmann : Could you review the above? Particularly numbers 6, 7, and 9

**Comment by ScottOppmann** [comment]
@CTLocalGovTeam @allisonmuise 

My comments:

The location field should support any value (address, parcelid, etc.) the user enters in to the search box.  In other words, if the organization configures a map with an address search plus layer search parameters, it should store the layer values too.

Question:

If the user clicks on the map or uses the current location, could we have an option that uses a reverse geocode to populate the location field?  If possible, we should make this a configurable option as well.

**Comment by CTLocalGovTeam** [comment]
@ScottOppmann @allisonmuise 

Instead of storing the text that user enters in to the search box, how about we store the result that the user selects from the list? This will be a standardized form of the result that's returned by the geocoder or the actual attribute value in case of layer search. Does this make more sense?

Yes, we can have an option to reverse geocode and populate the location field. We can also make this a configurable option. The only thing we need to consider while using this feature is that with geocoding, we have a way of letting users know that 'no results were found' for an address input. However, in this case, we don't have that. User may click on map and a reverse geocode may not return an address and the user expects that the location field will be auto-filled.

![image](https://cloud.githubusercontent.com/assets/2959186/13252436/a9bd45e4-da5c-11e5-9c64-2e625795a359.png)

**Comment by allisonmuise** [comment]
>1. Add a configuration option to select field to store location

Correct

> 2. This field will be assumed available in all layers, similar to Votes field.

Correct

>3. If field is not present in any layer, then this feature will not be triggered for that layer

Correct

>4. The location field should be of string data type. For location field other than string type, feature will not be triggered.

Per Scott, any field type should be supported. If the value returned can't be written to the field due to a type mis-match, that is ok. We will suggest a text field in the documentation/configuration panel.

>5. The location field will be auto-populated when user adds a point by searching an address

Correct

>6. Both search boxes (main map and geoform map) will trigger this feature of auto-populating location field in report form

Correct. In order of priority: the search box on the form, the reverse-geocoded location from a map point, and the main map search result

>7. If user adds a point by searching an address and later clicks on the map to re-locate the point, the location field will be cleared

Populate the field with the reverse-geocoded location of the placed point. 

>8. If user adds a point by clicking on map, or using geolocation button, the location field will not be auto-populated

In these circumstances, attempt to reverse-geocode the point

>9. This feature of auto-populating location information will not be triggered for line and polygon layers

For lines and polygons, proceed as with points regarding the search results and geolocation button. If feature is drawn simply by clicking the map, can the app attempt to reverse geocode to the first vertex?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We wanted to discuss approach for following questions.

> 1. The location field should be of string data type. For location field other than string type, feature will not be triggered.

Per Scott, any field type should be supported. If the value returned can't be written to the field due to a type mis-match, that is ok. We will suggest a text field in the documentation/configuration panel.

**Approach** : 
Here we are still checking for string field. If user configures any other type of field it will be a problem. 
( EG : if user configures field which contains domain coded values, then the field will be shown as dropdown, in this case we cannot populate the selected address). So the functionality will not be triggered for other type of fields.



> 1. This feature of auto-populating location information will not be triggered for line and polygon layers

For lines and polygons, proceed as with points regarding the search results and geolocation button. If feature is drawn simply by clicking the map, can the app attempt to reverse geocode to the first vertex?

**Problems supporting line and polygon geometry :**

* To submit a feature of type polyline or polygon user always have to draw the feature geometry on map, he cannot directly use the searched/geolocated feature.

* In case of lines and polygon layer, user can draw the geometry anywhere else on the map although he has searched or geo located to his area of interest. So the searched/geo located address may not match with the exact address of drawn geometry.

**Proposed Solution :** 
* So in case of poly lines and polygons instead of using the address of the searched/geo located feature, we can easily use the first clicked point(to populate the address) while drawing the line/polygon geometry.


Please let us know your thoughts.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
For the location field type: The above approch sounds good. As long as the app gracefully handles (aka doesn't throw an error) if a field of another type is configured.

For the location of lines and polygons: The point you bring up is valid for points as well. This is ok. If a search term is used, please store that value. If there is no search term, fall back to the other options as outlined for points above.

**Comment by allisonmuise** [comment]
verified

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : This information is only being stored when the field is editable. This information should be stored regardless of the field settings in the popup.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Just wanted to confirm our understanding on this issue:

If the field is marked as non editable in popup and same field is configured as a location field, although the field is not displayed in geo form. We still need to store the reverse geocoded address in location field under the hood and add it to the feature once user submits a record through geo form.

**Comment by allisonmuise** [comment]
That is correct. It should behave like the User ID field.
