### ISSUE TITLE
"Like" button label wrong in Brazilian Portuguese (pt-br)

### ISSUE THREAD

**Issue by garys-esri** [Esri/crowdsource-reporter#165]
"Curtir" is what Facebook uses. It could also be "Gostei." "Como" isn't even close; it means "how."

**Comment by garys-esri** [comment]
Fixed in d580f58c72aa5c1dff874f6430dd38d6fbd1dc5b

**Comment by allisonmuise** [comment]
@garys-esri : Thanks Gary. There are a number of languages (DE/ES/ET/FI/FR/IT/NL/PT-BR) where this was mis-localized. Unfortunately, the fix isn't as simple as me (or you) putting in the correct strings (I tried that!). I have reported the errors to the localization team and I'm hoping to get them fixed for the next release.  

If you have access to devtopia you can track the issue here: https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/1060
