### ISSUE TITLE
Add option to use photo location for report location

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#205]
When a photo with exif information is added to a report, ask user if they'd like to use the location of the photo as the location of the report

(Scott Moore)

**Comment by sirws** [comment]
It would be great to show the location of the photo on the map and let the user know it is coming from the photo, and then allow the user to use that location, or use the GPS location, or tap on map to update the location.

**Comment by allisonmuise** [comment]
@sirws : do you have a user we can work with on this request?

**Comment by sirws** [comment]
I may, I just need to get a hold of her as she is out in the field this summer.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Could you look into the feasibility of this?

**Comment by allisonmuise** [comment]
approval to use this package granted 10/11/2017.
Adding this work to the 6.1 milestone

**Comment by ashishchoure** [comment]
@allisonmuise 

Here is the GIF which shows the implementation of using image location to report the issue.
We have added "Yes" and "No" buttons to allow the user to decide whether or not to use the image location.

![csr_location](https://user-images.githubusercontent.com/5525972/45758612-a0b75400-bc43-11e8-9d20-d32df75c3c08.gif)

As per our previous discussion's, we are using exif.js library to fetch the image location.
Please let us know in case of any changes or modifcations.

**Comment by allisonmuise** [comment]
can we make the size of this window a little more in line with the size of the message? both on mobile and on desktop,

I'd also like to change the message to 'Would you like to use the location of this photo?'

**Comment by allisonmuise** [comment]
After selecting a photo with location data on iphone, i don't see the little circle that indicates the report location, but the app knows the location because it lets me submit the report. I see the circle on Android.

**Comment by allisonmuise** [comment]
@ashishchoure see comments above

**Comment by ashishchoure** [comment]
@allisonmuise 

We can easily change the message to 'Would you like to use the location of this photo?'.

Regarding the size of the window, we have made some modifications in the size of dialogs due to the introduction of footer buttons. If we keep the original size of the dialog, then the dialogs with footer buttons (share and location dialog)  doesn't look good.

![image](https://user-images.githubusercontent.com/5525972/46782295-50fc1200-cd43-11e8-89fc-3621e0f89f23.png)
We can discuss this on tomorrows call.

**Comment by ashishchoure** [comment]
@allisonmuise 

We are able to see the circle which indicates the user's location while uploading the geo tag image in ios device (Iphone 7, ios version : 12).

Please see the GIF :

![csr_geotag](https://user-images.githubusercontent.com/5525972/46787031-4007cc80-cd54-11e8-86eb-41e3d4ca7c92.gif)

Could you please share the application link and device details (with ios version) on which the issue is reproducible.

**Comment by allisonmuise** [comment]
Yesterday I was seeing this on 2 different iPhones running iOS 10.2.1 and 11.0.3 using multiple devext apps. Today they are all working perfectly.....

I'm going to mark this verified

**Comment by skrishn** [comment]
@allisonmuise : added testcase
