### ISSUE TITLE
Make color of text on splash page configurable

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#219]

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

![image](https://cloud.githubusercontent.com/assets/2959186/18435987/becc164e-7913-11e6-9b9e-429e05a10354.png)


In the current implementation, "Or" text in the splash screen is displayed in black color and all the other text is displayed in white color.

If we apply configured color on "Or" text and the color is white then user will not be able to see the text  because of white color background (Image 1)

To avoid this scenario, we are thinking of displaying "Or" text always in black color as per the current behavior (Image 2) 

Please let us know your thoughts.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : All currently white content (including Guest and social buttons) should change to the set color. I would suggest making the 'Or' text either white or black automatically based on the luminance of the selected color.

I like the W3C-compliant suggestion in the answer in this SO post: http://stackoverflow.com/questions/3942878/how-to-decide-font-color-in-white-or-black-depending-on-background-color

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We can easily apply the configured color to text content in splash screen. But all the buttons(Guest, social media sign in and horizontal bar) are images, we cannot apply color to image. To achieve this we need to use font icons instead of png images. Switching to font icons will be considerable effort(~one week). As we need to create the font icons and redo the alignment and spacing.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam what about SVGs? would they work with less effort?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, actually font icons are created using SVGs. Creating a font icon makes it straightforward to apply the selected color, as it behaves just like any other font. Working with plain SVGs is possible, but less straightforward to apply color as compared to font icons.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
The goal is to make it easier for people to find photos that will work for the splash page. Currently the photo needs to be fairly dark/saturated otherwise the text & icons don't display.

In the interest of finding a less time-consuming way to make this easier for users, how about the following

2 options for title color: White text or black/dark grey text. The white text would have a slight dark 'fog' behind it to help it stand out against any variation in color/saturation in the photo, and the black text would have a slight white 'fog' for the same purpose.

Something like this (please excuse the terrible paint-style photoshopping job on the text/icons!!)

![whitetext](https://cloud.githubusercontent.com/assets/2752195/18517228/7a9dccae-7a50-11e6-8150-6f06d3a7b2cf.png)

![blacktext](https://cloud.githubusercontent.com/assets/2752195/18517229/7c7d1fca-7a50-11e6-9718-5d79e095fc79.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise How about exposing some configurable options, so we can provide more flexibility to users when they are working with splash screen. We are thinking we can expose three configuration options:

1. Text color - user can set this using a color picker
2. Icon-background color - user can set this using a color picker
3. Icon-foreground color - only two options available; white and gray or some more. Pre-rendered images have to be used as we cannot change the color of an image on-the-fly.

Here's an example of what it would look like with lighter images as the splash background.

![image](https://cloud.githubusercontent.com/assets/2959186/18638147/adda28fa-7eac-11e6-8a6a-618b63e574ff.png)

**Comment by allisonmuise** [comment]
I like it!

**Comment by allisonmuise** [comment]
@CTLocalGovTeam This all looks great, but there is one piece of this page that is not being affected by the color changes - the horizontal line between the title and subtitle. Can the color of this line be set to match the image foreground color?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

This is minor change and we can deliver this in upcoming code drop.

**Comment by allisonmuise** [comment]
verified
