### ISSUE TITLE
'Feature cannot be displayed' in My Reports

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#247]
repro steps:
1) Apply a filter to a layer in a map that can be viewed in Reporter. 
2) Sign in to reporter using AGOL/social credentials
3) submit 2 reports to the layer with the filter. 1 that meets the requirements of the filter and 1 that does not.
4) open My Reports
5) select each feature. Both features are visible on the map and the attributes of both features are displayed, but the feature that does not meet the requirements of the filter also throws the prompt 'Feature cannot be displayed'.

As previously discussed, it is expected that features that don't meet the filter requirements will display in this view, but why is this message appearing when the feature is visible on the map and it's attributes are accessible?

repro app:
http://arcgis4localgov2.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=261c0304dea9410697cd7a03933361e6

use the cw-reporter map. The editable layer in this map contains the filter PUBLICVIEW is Yes.
I will send AGOL credentials via email.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are investigating this issue and we will keep you updated.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

As per our design, the 'Main Map' and 'Issue List' is always in sync. The filters applied in the web map are only honored in 'Issue List'. Where as in 'My Issues' all the features reported by the signed in user are  displayed irrespective of the filters. Hence, this is not in sync with the map or issue list.

Due to this, the features reported by user which are outside the filter will be available in 'My Issues' and not in 'Main Map' and 'Issue List'. 

So, when user selects feature(outside the filter) from 'My Issues', the app shows details of the issue, but fails to highlight the feature on 'Main Map' since it is filtered out and not available on the map. Because of this app displays the error message "Feature cannot be displayed".

Even in cases where users (guest or authenticated) submit an issue, and if its outside the filter, it’s always removed immediately from the map, but you can still see it in my issues.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : but the features ARE being displayed on the map in this view.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

As described in our comment above, It is an expected behavior when a filtered issue is selected from 'My Issues' you will see the details but the feature will not be displayed on the 'Main Map' and the app displays the message "Feature cannot be displayed".

> @CTLocalGovTeam : but the features ARE being displayed on the map in this view.

We investigated this further and found that the filtered issues selected from my issue's are getting added on map and it disappears again when you select the layer. This is minor bug where the filtered feature is getting displayed on the map(This was introduced during the implementation of 'Geographical Filtering'). We have found a fixed for this issue and we are testing it at our end.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Please don't fix this by removing those points from the map in this view.

This view should be a way for users to review all their reports, and the expected behavior is that all items (regardless of filter) are listed AND visible on the map. 

If this can't be done for this release, I will set the milestone for this issue to 5.1

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

The reports in 'My Issues' screen can come from multiple webmaps, so it may not be possible to load all of them on the map at once.  So we have to display them one at a time when user taps on a report.

Here is our approach to help users visualize and work with the reports submitted by the user regardless of filters:

1. On click of report row in My Issues, if feature is outside filter, it will be added to map and issue details screen is displayed
2. If user clicks edit icon in details view, geoform is displayed and user can submit updates to this issue
3. If feature is still outside filter after editing, then it will be removed from map and 'My Issues' screen is displayed with that feature still available in list. User can click to view that again.
4. If feature is inside filter bounds after editing, it will remain on map and 'My Issues' screen is displayed with that feature available in list.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Let's discuss this in the status call

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 

Per discussion on our call this morning, please implement the strategy you described above and demonstrated this morning. 

This behavior is an improvement of how the app handles this scenario currently, but I will listen for user feedback on how it can be further improved in a future release.

**Comment by allisonmuise** [comment]
verified
