### ISSUE TITLE
Cannot click on Submit button text

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#249]
Previously, the entire submit button was clickable - both the text area and the rest of the button.

Now, only the button surrounding the text is clickable - the text itself is not recognized as part of the button.

The entire button area - including the text - must be clickable.

cc @skrishn

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are not able to reproduce the issue. We tried with "+ Submit a Report", "Report It", "Update" and "Update Comment" buttons but all buttons "Click" event works fine.

![click_issue](https://cloud.githubusercontent.com/assets/2959186/20206877/824f9a86-a809-11e6-98f2-699305cb71f0.gif)

Can you please share the app link and the browser details where the issue is reproducible.

**Comment by skrishn** [comment]
Sorry guys - it was an error on my part coz i had some browser extensions enabled. I cant repro the issue after disabling extensions and restarting machine.

**Comment by allisonmuise** [comment]
👍  Thanks Suba
