### ISSUE TITLE
hide editing buttons when user doesn't have editing permissions

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#252]
(reported from Holistic)
When accessing the application through an ArcGIS account that does not have editing capabilities, attempting to submit a report, vote, or submit a comment throws a browser error. Hide the submit, vote, comment, edit, and delete buttons  when the user does not have editing permissions, including when it is a level 1 account.

@CTLocalGovTeam : What is the LOE for this? Ideally it would get fixed this release, but I will push if that's not possible.

**Comment by allisonmuise** [comment]
use cases where editing must be restricted:
- [ ] Authenticated AGOL user does not have editing capabilities (includes Level 1 users)
- [ ] Editing is restricted to members of a group containing the layers

None of these apply if the layer is shared with Everyone

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We looked at the code that Mike shared. It is part of web app builder (includes core jimu dijits) and will need considerable effort to port to crowdsourcing apps. 

We are trying to devise a simpler approach to implement this. Here are the details.

1. As a first step we get user privileges when user signs in
  * features:user:edit - editing is allowed
  * features:user:fulledit - editing is allowed only for owner/org_admin if editing disabled at the service. Works only for webmaps where layers have been added with full control. This may be a challenge to implement since, on app load, the layers are filtered on the basis of their capabilities. When editing is disabled at the service, but the webmap is created with full control by the owner, we don't see any capabilities stored in the webmap item data (JSON). In other cases, we see webmaps do store the capabilities which correspond to ones available at the REST end point i.e., 'create,query,editing'.
2. Find if a layer is "public" or "private". 
  * To do this we need to find the itemID of the feature layer. 
  * Then get itemInfo and read the "access" property of the feature layer item
  * **Note:-** The itemID is not available if a layer is added by URL in the webmap
    * In such case, we'll have to treat them as public layers, **is this ok**?
3. If layer is "public" then edits will be allowed regardless of user privileges
4. If layer is "private" then 
  * disable controls if user privileges do not allow editing

These updates need to be implemented in multiple places in the app viz., preparation of webmap list, selection of layer from webmap, geoform and comment form. The same applies to crowdsource manager too.

We cannot include this in 4.4 release as this looks like a moderate LOE and moderate risk update. 

Please let us know if the approach looks ok.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : OK, I'll push to 5.1 and let you know on the approach later.

**Comment by allisonmuise** [comment]
1. 
- yes, this sounds good,
- don't worry about this scenario for now. Other templates do not support editing on otherwise uneditable layers when they are added to the map with full editing control.

2, 3, 4: AGOL is attempting to handle this at the API level. Let's not worry about this at the app level for now.

**Comment by CTLocalGovTeam** [comment]
Here is our approach to implement the suggested option :

When user logs in with AGOL account, the app will get user's privileges.
1. If user is **not a 'Level 1' AND has "features:user:edit"** privilege, app will allow user to edit the features in reporter/manager application 
 2. If User is **'Level 1' OR "features:user:edit"** privilege is not found then app will hide editing buttons.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : You should be able to simplify this logic a bit. 

A Level 1 user will never have editing capabilities so testing for features:user:edit should be enough.

**Comment by allisonmuise** [comment]
verified
