### ISSUE TITLE
comments disable over https

### ISSUE THREAD

**Issue by ccrozek** [Esri/crowdsource-reporter#279]
comments disappear when viewing a reporter app over https vs just http. I noticed this on my own [demo site](https://gisappsecure.ewashtenaw.org/public/CSR/)'s "testesri" map as well as ESRI's own [Try It Now app](http://www.arcgis.com/apps/CrowdsourceReporter/index.html). If you add the "s" in the URL, the comments and comment button disappear. Gallery and Voting appear to be unaffected.

**Comment by allisonmuise** [comment]
@ccrozek Could you work with Esri Support Services on this? I suspect is has to do with the fact that you are reaching out to a service that is not https from an app that is. The will be able to troubleshoot this with you further an identify if this is a bug in the application, or expected behavior in a mixed environment.

**Comment by ccrozek** [comment]
@allisonmuise ah, you're right. sorry. I wasn't getting a mixed content warning, but when I switched all the services to https, now I'm seeing comments in reporter. thanks!

**Comment by allisonmuise** [comment]
awesome! glad that helped!
