### ISSUE TITLE
The I agree Button Not Functioning Properly

### ISSUE THREAD

**Issue by walzjc** [Esri/crowdsource-reporter#316]
Hello,

The I agree / Vote button was working properly. I added a few more fields and now the I agree / Vote button no longer works. I get the following error. When I stared over from scratch it worked fine again until I changed the edit and display settings. Any ideas? 
![image](https://user-images.githubusercontent.com/17415343/29779015-de965076-8bd6-11e7-9382-42ce6c3060c0.png)

**Comment by allisonmuise** [comment]
@walzjc : are there any error messages in the browser console?

**Comment by walzjc** [comment]
Unfortunately, no.

**Comment by allisonmuise** [comment]
Changing the display/edit setting shouldn't have any impact. The behavior you are describing is most commonly caused by not enabling Update capabilities on the service. If you have full editing permissions enabled on the layer, try contacting Esri Support Services or your distributor for help. They will be able to take a look at your app with you to troubleshoot.
