### ISSUE TITLE
Sorting the maps

### ISSUE THREAD

**Issue by Carolinercraig** [Esri/crowdsource-reporter#321]
Hello, is there a way to sort webmap in the list? For example, I created different webmaps with the name of the months, October, November, December, January....However, this would tend to sort it by the name instead of by the month in order. Is there a way I can do this?

**Comment by allisonmuise** [comment]
@Carolinercraig you can sort the maps by any of the options that are available for sorting the group that contains the maps. 

![image](https://user-images.githubusercontent.com/2752195/32017473-afe8c740-b97b-11e7-938c-0f8aeb577f0e.png)

**Comment by Carolinercraig** [comment]
Hi,

We need it to be able to sort by months as I have mentioned before.  This
will not do that for us.
For example, each webmap will have the month name and year, so it needs to
go in order with the most recent.

Also, under each month, the subcategory and features will need to be
ordered by the submission date. We really need this sorted out in order for
the app to have a logical time frame.

Thanks,
Caroline

**Comment by chris-fox** [comment]
@Carolinercraig, working within the current constraints of the application you could consider the following naming convention for your web maps to have them sorted by year and month in descending order.

![image](https://user-images.githubusercontent.com/6796763/32071045-0ebbceee-ba5c-11e7-8241-3e849a5275de.png)

In addition, you can currently sort the reports in the map using a date field in the layer:

![image](https://user-images.githubusercontent.com/6796763/32071203-8f4a9ee6-ba5c-11e7-98b8-423ecc793e63.png)

**Comment by allisonmuise** [comment]
@Carolinercraig to add to @chris-fox 's note above - please note that sorting the reports by a field value is only applied when the user has not shared their location with the app. If they have shared their location with the app the reports will always be sorted by proximity, so that the reports that are nearest to them are at the top, and those that are furthest are at the bottom.

**Comment by Carolinercraig** [comment]
Hi,
Where did you take the screenshot from? I have not been working with any configurable template as  I had downloaded the files directly from github and updated the group ID.  I do not know where to go to find where you had taken your screenshot.

Thanks,
Caroline

**Comment by allisonmuise** [comment]
Configuration of the app when hosting it on a web server is documented here: http://solutions.arcgis.com/local-government/help/crowdsource-reporter/get-started/host-on-your-web-server/

The parameters shown above are equivalent to the sortOrder and sortField values in the defaults.js file.

**Comment by Carolinercraig** [comment]
There is no sortField  nor sortOrder in the defaults.js file .... I found in the  template.js and template-config.js file, however this does not pickup the field to sort.

**Comment by chris-fox** [comment]
@Carolinercraig, looks like the fields are called 'sortingField' and 'sortingOrder': 

https://github.com/Esri/crowdsource-reporter/blob/master/config/defaults.js#L105

**Comment by Carolinercraig** [comment]
Hi,  Thanks for the information. I tried it and unfortunately it is not doing anything. I added the fields as follows:

 "sortingField" : "SubmissionDate", //Field can be of type integer, string or date		
    "sortingOrder" : "DESC", //ASC or DESC

SubmissionDate is the name of the date field.  I even tested with the Title field and seems it's not doing anything to the order of the features. Here is my live app link:  https://www.gis.com.bz/app/belizefloods/

**Comment by allisonmuise** [comment]
@Carolinercraig this appears to be a customized merge between Reporter (this app) and Crowdsource Storymap, which is an entirely different application.  Because of the level of customization, I'm sorry but we can't troubleshoot this issue.  I've confirmed that sorting is working in Reporter as designed (and described above), but your list appears to be coming from the storymap and I don't know if or how that app supports sorting.

**Comment by chris-fox** [comment]
@Carolinercraig, to add to @allisonmuise, I took a look at your code and it has been modified quite a bit from the original crowdsource reporter application code. Below you can see in the original code when the layer is initialized it checks for a sort field:

https://github.com/Esri/crowdsource-reporter/blob/33cc2dbecc14c98284b9d8ba705a72e69e7eaf7b/js/main.js#L2060

In your code this function doesn't exist and is never called. There are quite a few changes from the original code so it isn't a simple change to make this work, it would require a developer to go in an add the sorting capabilities back.

https://www.gis.com.bz/app/belizefloods/js/main.js

Otherwise you could download the original application from the repo and configure it to work with your group and webmaps.

**Comment by Carolinercraig** [comment]
I had downloaded the code I am using directly from the github download button. Please give me the link I am to download from.

**Comment by chris-fox** [comment]
@Carolinercraig, I did some searching around and it looks like your code was downloaded from a fork of this repro owned by @jpeterson, his repo is https://github.com/jpeterson/crowdsource-reporter.

This repo, https://github.com/Esri/crowdsource-reporter/ is the officially supported repo by Esri. You can download this repo's code from the link below:

https://github.com/Esri/crowdsource-reporter/archive/master.zip

Be aware that this application will look different from the application you currently have because there were quite a few changes made by @jpeterson in his repo.

**Comment by Carolinercraig** [comment]
Thank you! I'll look into it and let you know.

**Comment by Carolinercraig** [comment]
This issue still has not been resolved unfortunately,  I tried with the master file and the sorting still has not take effect. I tried with my SubmissionDate field and Title. 

Using the master file:
https://www.gis.com.bz/app/crowdsourcereportertest/

**Comment by chris-fox** [comment]
@Carolinercraig, it is working for me, see the screenshot below. It is possible that you shared your location with the application. You are typically prompted when the application first loads if you want to share your location. If you share your location that the application it will return the features sorted in the order from closest to furthest away.

Prompt asking if I want to share location:
![image](https://user-images.githubusercontent.com/6796763/32172705-e78ad3f2-bd52-11e7-9923-f78814b7573b.png)

Screenshot with location unshared (Note location icon in the bar next to the star has a red x):
![image](https://user-images.githubusercontent.com/6796763/32172815-4be6fe34-bd53-11e7-9e80-8c441bfa1be1.png)

**Comment by Carolinercraig** [comment]
Hi Chris,

Thanks for the information. So it seems that when the app location is NOT shared,  then it is indeed sorted. We would have needed it to sort this way even if the location was shared. I thought that this is something we would have encouraged our users to do when they participate.  Any way around this?

**Comment by chris-fox** [comment]
Unfortunately there is not a work around to this without modifying the application code.
