### ISSUE TITLE
save app to homescreen graphic is screenshot of app

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#331]
The 'save to home screen' graphic on mobile devices should be the app logo

@CTLocalGovTeam LOE to address this? Would it be possible to deliver this for 5.4 without disrupting current dev timelines?

**Comment by allisonmuise** [comment]
City of Ames

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

The current approach to show home screen icon is as follows : 
1. If fav icon is configured, show it as a home screen icon.
2. If fav icon is not configured, check if app icon is configured and show it as a home screen icon.
3. If both fav icon and app icon is not configured, show group icon as a home screen icon.
4. If all three are not configured, show default fav icon as a home screen icon. 


If we try to create home screen icon once sign-in screen is displayed, app's screenshot is used as home screen icon. However, creating a home screen icon when we are on main page (once web map list and map is loaded) results into showing fav icon as shortcut icon (expected behavior).

So, the issue is reproducible when user creates a home screen icon once he is on sign-in page.
Please confirm if you are also observing the same behavior ?

We are trying to find the root cause and we will get back to you as soon as possible.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We have fixed this issue on our end and it is in testing phase. We are planning to deliver the same on this Thursday.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Yes, that is what I am seeing. Thanks!

**Comment by allisonmuise** [comment]
@CTLocalGovTeam I missed verifying this before the release. The icon that is used for the home screen is extremely low resolution. Is there a way to use a graphic that looks better than this? I'd like to patch for this early next week, if possible.

![image-1](https://user-images.githubusercontent.com/2752195/33739492-289279fa-db52-11e7-8a8b-e8d790855315.jpg)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We have two options to change the graphic.

1.  We can easily change the graphic by changing the `applicationFavicon `image in configuration file.
`applicationFavicon": "/images/app-icon.png`
app-icon.png will work for both favicon and shortcut-icon and it is already available in "images" folder.
Screenshot  : 
![picture2](https://user-images.githubusercontent.com/2959186/33756114-ef9be9c4-dc19-11e7-92d1-fcc63bdaefdf.jpg)

2. We can override the existing favicon.ico image with high resolution .ico image file.

Please let us know your preference. We will make the suggested changes and provide you a pull request on coming Monday.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam It seems like it would make more sense for the app to use whichever file is configured for the app logo as the homescreen button, not the favicon graphic. If this isn't possible, let's go with option 2.
