### ISSUE TITLE
support URL parameters to access specific reports

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#354]
support same parameters that were added to Manger
https://github.com/Esri/crowdsource-manager/issues/92 
related to #157

**Comment by allisonmuise** [comment]
verified!
This is pretty cool :)

**Comment by aparveen** [comment]
@ashishchoure We found out a bug where if you specify the oid in the url, the url does not open to the specific report but if you use selectedFeature instead of oid it works, Could you please fix it so that it works with both oid and selectedFeature.

**Comment by ashishchoure** [comment]
@aparveen @allisonmuise 

Currently application is looking for following URL parameters to selected feature : 
1. `webmap`
2. `layer`
3. `selectedFeature`

Application is not searching for `oid `URL parameter. This is the reason the report is not getting opened after adding this parameter in the URL.

This functionality was designed as per the Esri/crowdsource-manager#92. However, the crowdsource manager uses `oid `parameter instead of `selectedFeature`.

We can easily change the parameter name to `oid`. By doing this we will make sure it is exaclty same as crowdosurce manager.

Keeping two different parameter's for accepting object id is not recommended as it will complicate the things more.

This requires minor code change and it is low LOE.

**Comment by aparveen** [comment]
@ashishchoure Thank you for investigating this issue, I discussed this with Allison and as you recommended we both think we should keep it as it is, and only update our doc. I will close this issue after we update out doc.

**Comment by aparveen** [comment]
2777

**Comment by LindsayThomas** [comment]
Assigned to Aziza

**Comment by aparveen** [comment]
This issue is logged in to Solution repo for doc update. 7711
