### ISSUE TITLE
reporter not displaying vector basemaps

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#363]
When the map uses a vector basemap, the map does not draw correctly in Reporter

**Comment by allisonmuise** [comment]
@ashishchoure This was impacting all our try it live apps around the time of release. I'm also not seeign this issue any more so will close.

**Comment by allisonmuise** [comment]
@ashishchoure Users are reporting this issue with our try it live applications as well - both Reporter and Manager. Could you take another look? We are seeing on mac using chrome and safari and windows using chrome. no errors in the console. Browser caches have been cleared. Sometimes it loads; sometimes it doesn't. You may need to refresh a few times to see the issue. It appears to be more consistently a issue in Manager than Reporter, but I have definitely seen it in both

https://www.arcgis.com/apps/CrowdsourceReporter/index.html?appid=106f109bd2394496bcc69d486523ffc5

https://www.arcgis.com/apps/CrowdsourceManager/index.html?appid=b10494ecdb4c447fba1471cc889f9eeb

**Comment by ashishchoure** [comment]
@allisonmuise 

We are able to reproduce the issue.However, it is not always reproducible.

If the vector base map is not loaded we see an error message in console.
![image](https://user-images.githubusercontent.com/5525972/46198978-5c0a7780-c32b-11e8-9e61-fc54a1c0b502.png)
 
We think this is not an issue from Reporter/Manager app. The code fails in the `VectorTileLayerImpl.js` file in JS API.

Could you please confirm if you see the same behavior in the other applications.

**Comment by allisonmuise** [comment]
@ashishchoure - no, this is only being reported in these two apps. I opened several other web app templates and WAB apps this morning to confirm I don't see this issue with them, even with multiple refreshes.

**Comment by allisonmuise** [comment]
@ashishchoure any update on this? There is no sign of this issue in any other apps, and additional users are reporting this issue with reporter.

**Comment by ashishchoure** [comment]
@allisonmuise

We were planning to take up the remaining github tickets after implementation of accessibility.
Should we take this issue on high priority and then resume accessibility?

**Comment by allisonmuise** [comment]
@ashishchoure no, that's fine. Just wanted to make sure this wasn't forgotten as it is high priority for december. If necessary we can address this after string/code freeze.

**Comment by ashishchoure** [comment]
@allisonmuise

We did good amount of testing with vector basemaps and we didn’t see the issue.

We tried on multiple machines. Even after clearing the cache the app seems to be working as expected.

This is just to update you. We will continue our investigation. Could you please try and see if the issue is still reproducible.

**Comment by allisonmuise** [comment]
@ashishchoure Yes, the issue is still reproducible. @ScottOppmann is able to reproduce it fairly reliably, as are customers and other Esri staff. Like you, I see it very rarely, but it's an issue that is still currently being reported by others.

Could it be a timing issue? That might explain why it's hard to reproduce.....I see it nearly every time someone tries to demo the app over skype.

**Comment by ashishchoure** [comment]
@allisonmuise
 
I also think it is timing issue. But i am not sure.
The last time i was able to reproduce issue was first time the app is being loaded in the browser. After that the app appears to be working as expected.
However, i was not able to reproduce the issue today.

**Comment by allisonmuise** [comment]
@ashishchoure Maybe try slowing your machine? run an instance or two of Pro....screenshare over a poor wifi connection...etc?

**Comment by ashishchoure** [comment]
@allisonmuise 

We are able to reproduce the issue consistently on slow network connection.

However, while testing the application we found that the vector basemaps are loaded in CSR  with JS API 3.24. The issue is reproducible from API version 3.25 (Regularly on slow network connection).
This is happening only with CSR application. 

Here are the link's for both the API versions. We have tested them on google chrome with Slow 3G option : 
- [CSR JS API 3.24](https://csslesxi9-vm3.cybertech.com/csreporter/CSR_3.24/?group=9a36b73d400141dca9cd0c5df3d18c08)
- [CSR JS API 3.27](
https://csslesxi9-vm3.cybertech.com/csreporter/CSR_3.27/?group=9a36b73d400141dca9cd0c5df3d18c08)

We think there are some changes in the vector tile implementation in the JS API. Could we get the `VectorTileLayerImpl.js` file for JS API version 3.24 and 3.27?

This will help us in understanding what has been changed and whether we need to add/update the code in CSR in-order to overcome this issue.

**Comment by allisonmuise** [comment]
Hooray for repro cases!!
I've places zips of the 3.24 and 3.27 (master branch) releases of the repos in the box folder with the WAB builds.

**Comment by allisonmuise** [comment]
@ashishchoure

**Comment by ashishchoure** [comment]
@allisonmuise 
### **Issue Description & Behavior:**
- The CSR is a group application template designed to work  only with webmaps in the group which have editable Feature Layers with Popup info. 
- In order to filter the items form the group we need to create each webmap and then in the response of argisUtils.createMap() function we decide to consider the loaded webmap as valid or invalid.
- So, we load all the webmaps in the group in the hidden div and once we get the response of argisUtils.createMap() function and complete the validation we destroy the map loaded in the hidden div and load only one selected webmap in a main map container which is visible in the app.
  - **Reason to destroy maps in hidden Div** -  _We need to destroy the hidden map as the map may have some layers with refresh intervals, which will results in unnecessary requests  fired and will have impact on apps performance._
- Meanwhile, when all the maps are being loaded, API fire’s request for the info of vector base map (e.g.  sprite.json).
- It is observed that when application is having multiple instance of map and if one of the map is destroyed while creating the other map the vector base map fails to load.

### **Observations with API :**
 - We are seeing this behavior starting from JS API 3.25 and only observed with the slow networks.
 - We observed few code changes in the API which points to cancel the requests in file ‘**VectorTileLayerImpl.js**’ in  ‘**_stopDisplay**’ function.  However, we are still  not able to point to the exact code which is impact the application to fail.

### **Fix at Application level:**
 - We can fix this issue if we destroy the maps once the main map is created and loaded completely.
 - We have implemented a fix which have minimum changes in the application and we are testing it.
  
It would be great help if we could have API teams input on this before finalizing the approach. We will share the sample to reproduce this issue and the fixed CSR app link via email.

**Comment by allisonmuise** [comment]
@ashishchoure go ahead and send me the fix for this issue. It doesn't seem likely at this point that we'll get a reviewer from the API team although I'll keep asking. I trust your code and we have a few days to test. If, for some reason, it causes issues other we still have time to roll back.

**Comment by allisonmuise** [comment]
verified
