### ISSUE TITLE
(More) changes to searching for a report location

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#367]
Is the search in the submission form already custom?

If so, would it be possible to display the search suggestions without sorting them by geocoder?
If that's not possible, in cases where only one geocoder is configured, could we hide the geocoder name, and just list the suggestions? 

(not necessarily for 6.4, just want to know if this is possible, or if it would involve taking an out of the box component and making it custom.)

**Comment by ashishchoure** [comment]
@allisonmuise
> Is the search in the submission form already custom?
- Yes. The search functionality in the geoform and main map both are customized.

> If so, would it be possible to display the search suggestions without sorting them by geocoder?
- We need to query each configured geocoder sequentially in order to get the result's. So, we cannot display all the results without sorting them.
  
> If that's not possible, in cases where only one geocoder is configured, could we hide the geocoder name, and just list the suggestions?
- Yes, we can implement this change. If only one geocoder is configured, the geocoder name and "+" sign will not be displayed and only the suggestions list will be shown to the user.

Question : 
Do you want this change only in geoform or in both the places (Main map and geoform) 

This is a low LOE ticket and we can implement this in 6.4 release.

**Comment by allisonmuise** [comment]
@ashishchoure Let's make the change in both places.

**Comment by allisonmuise** [comment]
verified
