### ISSUE TITLE
Add accessibility landmarks

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#377]
roll-over from accessibility issue from 6.4

**Comment by ashishchoure** [comment]
@allisonmuise 

Here is list of all available landmarks and how they can be applied to the various sections of the crowd source reporter application in order to make it more accessible: 

1.	**banner**: A region that contains the prime heading or the internal title of a page.
     - We can add this landmark to application header (**role="banner"**)

2.	**complementary**: Any section of the document that supports the main content, yet is separate and meaningful on its own.
    - I think we can add this landmark to legend and basemap gallery panel as they are supportive contents of main section. (**role="complementary"**)

3.	**contentinfo**: A region that contains information about the parent document such as copyrights and links to privacy statements.
    - Reporter app doesn’t have such a section. So, we will not use this landmark.

4.	**form**: A region of the document that represents a collection of form-associated elements, some of which can represent editable values that can be submitted to a server for processing.
    - We can add this landmark to geo-form and comment-form. (**role="form"**)

5.	**main**: Main content in a document. In almost all cases a page will have only one role="main".
    - We can add this landmark to the main container in the index.html page. (**role="main"**)

6.	**navigation**: A collection of links suitable for use when navigating the document or related documents.
    - Reporter app doesn’t have such a section. So, we will not use this landmark.

7.	**search**: The search tool of a Web document.
    - Reporter app doesn’t have such a section. So, we will not use this landmark.

8.	**application**: A region declared as a web application, as opposed to a web document. 
    - As per the Tao’s suggestion, we have already use this landmark for map div. (**role="application"**)


Could you please get it reviewed with Tao. His feedback will help us in identifying whether we are missing on any key points.

**Comment by allisonmuise** [comment]
Tao's reponse sent via email.

Sum: complementary is not necessary, others look good.

**Comment by allisonmuise** [comment]
verified
