### ISSUE TITLE
Remove tab order from legend & basemap gallery title & body

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#387]
![11-14-2018 2-09-55 pm](https://user-images.githubusercontent.com/2752195/48516892-80f27580-e819-11e8-85a5-6efa7ea40396.png)
![11-14-2018 2-10-08 pm](https://user-images.githubusercontent.com/2752195/48516893-80f27580-e819-11e8-9048-94388d735eb1.png)
![11-14-2018 2-10-28 pm](https://user-images.githubusercontent.com/2752195/48516891-80f27580-e819-11e8-80e1-055e669255b3.png)
![11-14-2018 2-27-57 pm](https://user-images.githubusercontent.com/2752195/48516895-80f27580-e819-11e8-8f75-b37d8e60bd97.png)

**Comment by allisonmuise** [comment]
This also applies to the basemap gallery

**Comment by ashishchoure** [comment]
@allisonmuise 

We have removed the tab index from header and body and now the focus will directly be set to close button once the respective panel is open.

Since we have removed the focus from the body, user will not be able to select the basemap through keyboard. This is just to update you.

Let me know if this sounds good or anything needs to be changed.

**Comment by allisonmuise** [comment]
@ashishchoure I will test and let you know if body focus needs to be restored.

**Comment by allisonmuise** [comment]
verified - the basemaps are navigable with the arrow keys and can be selected with a press of the Enter key
