### ISSUE TITLE
Form not populating with all fields

### ISSUE THREAD

**Issue by KubaSzostak** [Esri/crowdsource-reporter#418]
Crowdsource reporter requires only one simple symbol renderer. It's clearly stated in [documentation ](http://solutions.arcgis.com/local-government/help/crowdsource-reporter/get-started/create-layers/#symbology)but the app does not display any warning message if this requirement is not meet. In my case I had two fields "Summary" and "Description", both text, both with te same settings in "Configure pop-up" dialog. It was hard to realize that one field is missing because layer was published with wrong symbology.  

It would be great to see some warning message when this requirement is not meet.
Se also https://community.esri.com/thread/194540-crowdsource-reporter-form-not-populating-with-fields

**Comment by allisonmuise** [comment]
Because reporter is a group app that displays the content of a group, it is not possible to test each layer in  each map during the configuration process. Maps can be added/removed/edited at any time so such a test during configuration would be misleading at best. 

Additionally, while the most commonly sought behavior is the result of using only a single renderer when publishing the layer (you can symbolize the layer in the web map using a unique value renderer without issue as this isn't reflected in the layer JSON), I have seen valid use cases where layers were published with complex symbology, subtypes, etc, to produce alternative behaviors that better matched the needs of specific workflows. For this reason I would not want to prohibit the use of such layers at app run time.

In this case, we've decided that documenting the requirements for the most common workflow is the best option for helping users configure this application.
