### ISSUE TITLE
Popup sort order for required fields not respected in App

### ISSUE THREAD

**Issue by akung21** [Esri/crowdsource-reporter#426]
My feature layer has a subtype, domains, and fields that are required (nullable is false). When submitting an issue in the Crowdsource Reporter app, required fields do not show until I choose the subtype. Once I choose a subtype, the required fields appear, but they are not in the order configured in the popup on the webmap. The required fields always show up together at the top and in the opposite order that they appear in the popup configuration.

Is another way to order fields, or is this a potential bug?

Thanks!

**Comment by allisonmuise** [comment]
@akung21 This is a known behavior. We do not recommend using subtypes with Reporter because they create multiple feature templates in the layer. Reporter is not designed to work with multiple feature templates. When Reporter tries to draw the popup, it doesn't know what fields to show and what values are acceptable in them until the feature template is specified, which doesn't occur until after a subtype is selected.
