### ISSUE TITLE
Reporter to behave like Manager when hover over an attachment to show file name

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-reporter#439]
When more than one attachment is added, it provide no information about the attachment as it has a common thumbnail. We would like reporter to behave as manager, where when hovered over it shows the attachment name.

![image](https://user-images.githubusercontent.com/10148401/62636460-72d80e00-b8ee-11e9-8037-3d9d384e969c.png)
![image](https://user-images.githubusercontent.com/10148401/62636495-7ff4fd00-b8ee-11e9-955a-6c5681f31390.png)

**Comment by allisonmuise** [comment]
@chris-fox - I spoke with Aziza about this and she suggested reaching out to you.

We generally don't do things on mouseover in Reporter because it is really designed for mobile devices. Additionally, file names generated by mobile devices are not usually helpful in identifying media.

Would it perhaps be better to use the first frame of the video as a thumbnail with a super-imposed play button for videos?

**Comment by chris-fox** [comment]
@allisonmuise, I agree with you that the name won't be all that useful. I like showing the first frame of the view as a preview if that is possible.

**Comment by ashishchoure** [comment]
@allisonmuise 

 - In the current implementation, we show the predefined image for video attachment and thumbnail for attached image(same image with smaller dimensions) in gallery section. 
-  On click of image/video it opens the same in new tab.

Here is how it looks like : 
![image](https://user-images.githubusercontent.com/5525972/65424223-9ae0e980-de28-11e9-8246-7d9307c7d563.png)

- So, if we want to show the first frame of the video as thumbnail then we will have to render the video on in the gallery section.

**Comment by allisonmuise** [comment]
@chris-fox what do you think of this proposal?

**Comment by chris-fox** [comment]
@allisonmuise, i'm good with that

**Comment by ashishchoure** [comment]
@allisonmuise 

We can use HTML5 video tag, user can see the first video frame inside the video control. This works in desktop browsers. However, we observed some issues in the mobile devices.

**Android Device :** 
- The play button looks distorted. 
- We cannot see the settings option from which user can go to full screen mode. This is because of the limited height/width.
![image](https://user-images.githubusercontent.com/5525972/66815564-1e888480-ef56-11e9-9b47-cd94f1dbd405.png)

**iOS Device :** 

- We cannot see the video thumbnail and we can only see the white background.
- We cannot see the settings option from which we can go to full screen mode. This is because of the limited height/width.
![Screenshot 2019-10-15 at 1 22 05 PM](https://user-images.githubusercontent.com/5525972/66815802-8a6aed00-ef56-11e9-9a2a-fb9ce32e31a6.png)

Could you please let us know your thoughts on this?

**Comment by allisonmuise** [comment]
@chris-fox Could you review the comments above re: displaying the first frame of videos on mobile devices and let us know how you'd like to proceed?

**Comment by chris-fox** [comment]
I am less concerned about the the image/preview than i am playing the video. The full screen play would seem to be important here for usability on a mobile device. 

Does this limitation occur in the current release with playing videos on a mobile device? Can we do some more research to see how we could play in full screen.

**Comment by ashishchoure** [comment]
@chris-fox 

The first section of this [comment](https://github.com/Esri/crowdsource-reporter/issues/439#issuecomment-534071457) explains the current implementation of showing/playing  videos in the application.

**Comment by chris-fox** [comment]
In that case IMO i don't think it is worth sacrificing the ease of playing the video on all devices for the ability to preview the first frame of the video in some devices.

**Comment by ashishchoure** [comment]
@allisonmuise @chris-fox 

Could you please let us know how to proceed on this gituub ticket.

**Comment by allisonmuise** [comment]
based on the conversation above, no changes required at this time.
