### ISSUE TITLE
i18n - crowdsource reporter app - display language

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#445]
Currently apps display with browser language UI for anonymous users. It is expected behavior.
When I sign in to Crowdsource Reporter app with my ArcGIS user account I expect to see this user's language UI. Currently it continues respecting my browser language and ignores my user's language, it is not good.

**Comment by allisonmuise** [comment]
2964

**Comment by allisonmuise** [comment]
I am not seeing this change.
My browser language is english, and my ArcGIS profile language is French. I would expect the following:
- sign in screen to load in english
- app accessed as a Guest to load in english
- app accessed by signing in to my account to load in french

**Comment by allisonmuise** [comment]
@ashishchoure

**Comment by ashishchoure** [comment]
@allisonmuise 

- In the morning (IST) we were able to reproduce the issue. However, we got the expected result in the evening (IST). Is devext being updated? We have tested this implementation on [devext](https://cybertech.mapsdevext.arcgis.com/).
- In addition to this, we tested the same functionality on **AGOL** and **Portal** and everything was working as expected.
- Could you please check and let us know if the issue is still reproducible. If yes, please share the application link.

**Comment by allisonmuise** [comment]
@ashishchoure I can still see the issue this morning. I have sent a URL and credentials via email. Devext rebuilds every night, piece by piece, so it doesn't surprise me that things behave differently at different hours. Fun!

**Comment by ashishchoure** [comment]
@allisonmuise 

As discussed on yesterday's call, we analyze this issue and below are our findings : 
- We will consider user display language if the user is singed in.
- We also found that, we cannot keep the user language `blank `in AGOL.
  - So, we are planning to always look for user's display language and load the same in reporter application.
  - However, in case of any unforeseen error we will fall back to organization's language. 

Please let us know your thoughts.

**Comment by allisonmuise** [comment]
@ashishchoure This makes sense to me for users who sign in with the ArcGIS option.

**Comment by allisonmuise** [comment]
verified
