### ISSUE TITLE
Remove horizonal constraint on icon

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#46]
long icons are being compressed horizontally. Allow them to expand next release

**Comment by CTLocalGovTeam** [comment]
@allisonmuise App logo will be restricted with height of the title bar so that it can spread horizontally. However maximum limit for spreading the icon is 150 px less than device width so that application name can be displayed with ellipses alongwith menu icon aligned right. Please refer the below mockup. 

![image](https://cloud.githubusercontent.com/assets/2959186/7269397/45da7b8a-e8f1-11e4-9871-7667afd8ba82.png)

**Comment by allisonmuise** [comment]
This makes sense in cases where a title has been configured.

If no title is configured, the graphic should be able to expand to the menu icon.

If the graphic is longer then the available space, is it possible to crop/hide the graphic after the menu button rather than compressing it vertically?

**Comment by CTLocalGovTeam** [comment]
@allisonmuise If title is not configured then the graphic will expand till menu icon. The aspect ratio of the graphic will be maintained using the height.

Graphics are image files so we will not be able to crop it or hide the part of it that cannot fit in available space. In this case, we do not have a choice but to show the graphic in available space without cropping or hiding part of it.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Please find the mockup when  no title is configured.

![image](https://cloud.githubusercontent.com/assets/2959186/7296900/70ffd27e-e9e1-11e4-8a62-884efdea061a.png)

**Comment by allisonmuise** [comment]
ok

**Comment by LindsayThomas** [comment]
@allisonmuise When no title is configured in the configuration panel of the application, then the application automatically defaults to use the title of the application item in AGOL.

**Comment by allisonmuise** [comment]
OK I will fix this in the config files.

**Comment by allisonmuise** [comment]
verified
