### ISSUE TITLE
Display app name in browser tab

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#51]
browser tabs currently say 'Constituent Engagement'

**Comment by CTLocalGovTeam** [comment]
@allisonmuise We will include the fix in sprint 1.

**Comment by LindsayThomas** [comment]
Verified a Custom Name will appear in the Browser Tab.

@allisonmuise Note: The URL to the application is displayed in Browser Tab initially. Once you click on a sign in option then you get the Custom Name in the browser tab. I *think* this is expected behavior with the application being hosted the way it is. I am closing the issue but reopen if this isn't correct.
