### ISSUE TITLE
When geolocation is enabled, reports/features are not updated with new search that is outside of the geolocation area

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-reporter#515]
With the current design, geolocation when enabled takes precedence, and shows reports in that area, but we would like to honor and show reports when a search performed using search widget is outside of the current location.

https://stategovernment.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=6236a76e3a374232985b4444f9c840a1

- Search 'Baltimore' using search widget. Notice that the features renders and popup can be viewed. 
- Enable geolocation and search Baltimore again, but features are not rendered

Question:
Is there a way to identify if the search term is outside of the current location?. The search term might have multiple suggestions, and if users hits enter without choosing from the suggestion, assuming the result from current location. In such scenario ( or always) we can show an alert message that the search is outside of the current location.

Please share your thoughts on how we can implements this. 

cc @aparveen

**Comment by sumitzarkar** [comment]
@aparveen  

Let's discuss and finalize the approach on this.

**Comment by sumitzarkar** [comment]
@aparveen 

As discussed on the call here are the options we see to improve the user experience:

### Option1: 
 - Only update the string and add hint text regarding the option in the configuration. If required make this checkbox checked by default.
   <img src="https://user-images.githubusercontent.com/22743029/136910297-6eefb15a-ef5d-458b-89ff-9a415e46536e.png" >


### Option2:
 - On load show a popup to confirm if the user wants to show features around the current location or show all features from the layer.
 - If required we can add a settings button in the app header which will open this popup to allow users to change the settings at runtime.
 

### Option3:
 - Add Switch in the features list to turn on/off the functionality to show features around the current location. 
 - If this switch is turned off all the features from the layer will be shown
![image](https://user-images.githubusercontent.com/9443956/148586552-19ddeca4-ffc4-427c-9549-0a35f65aad2c.png)


___



- Option1 - Don't have any impact/risk since no code change is involved. we just need string changes in the configuration for this.
- Option2 & Option3 - This is a High impact and High LOE change as it involves UI and functional change which will also need major testing efforts.

Please let us know your thoughts on this

**Comment by aparveen** [comment]
Adding our conversation to this issue clarifying the actual functionality of the parameter.

Aziza- By default if location of the device is enabled (in browser), Reporter will honor the current location right?
CT: If above checkbox is unchecked and if location of the device is enabled then Reporter will honor the current location

Aziza-  This particular parameter will only stop showing the pop up from the browser when checked and in this scenario users will not have the option to turn off the geolocation at runtime. Is this right?

- No, this parameter is for disabling geolocation. i.e. If this is checked users current location will not be used and user can see all features from the layer. If this is unchecked the users current location will be used and only features around that location will be shown in the list.
- Browser display the popup when any website tries to use geolocation and we as a developer don't have any control over the message shown by browser, this is completely controlled by browser.
- And, in some browsers we have option to allow some sites to use geolocation and then that popup will not be shown anymore.
- This is the reason we proposed option 1, in which we recommended to update the strings for this checkbox.

**Comment by sumitzarkar** [comment]
@aparveen @skrishn 

Please suggest the strings changes required for this ticket
![image](https://user-images.githubusercontent.com/9443956/150103248-d00a7c70-b258-4c11-a5c2-b7eeaddb9f1c.png)

**Comment by aparveen** [comment]
@skrishn what do you think about the following strings, any concern, suggestion?
![image](https://user-images.githubusercontent.com/10148401/150184227-0396b6f4-0540-4129-8291-e12bb68af8c2.png)

**Comment by skrishn** [comment]
@sumitzarkar 

![image](https://user-images.githubusercontent.com/3836616/150236869-8a825a26-682f-4a47-a31e-7747c587bca2.png)
Please refer to the image, and make the changes as marked

- Replace text for 1 to 'Geolocation settings'
- Replace text for 2 to 'Allow users to access the application without using their current location‎'
- Replace text for 3 to
'By default, the application will prompt the user to access their current location. When users share their location with the application, only reports within this radius will load. Users can expand this search radius incrementally in the application. Define the radius of this initial search for nearby reports. ‎When checked, the application will not use the current location.'
- Reorder 2 and 3

cc @aparveen

**Comment by sumitzarkar** [comment]
@skrishn  @aparveen 

### Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

### Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | Yes
Have Runtime changes?​ | No
Impact on RTL | No
String Changes | Check for strings changes in the configuration panel

**Comment by aparveen** [comment]
Verified
