### ISSUE TITLE
Search widget is not working with custom geocode locator

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-reporter#516]
Custom geocoder service is not working properly within the Crowdsource Reporter application. It worked before. It works well within web maps and other applications, but not in the Crowdsource Reporter. When an address is entered and result is chosen, it will not zoom to that address within the application. The ArcGIS World Geocoder is working fine within it, but it is cumbersome for our customers to use. Our geocoder service is:
https://gis.whud.org/arcgis/rest/services/Public/SingleHouse/GeocodeServer. 

Addresses Support tried are 109 Manor, 3053 Worsham Springs, 317 Rockland, and 200 Business Park
I am seeing console error.

Test app: https://stategovernment.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=6236a76e3a374232985b4444f9c840a1

![image](https://user-images.githubusercontent.com/10148401/137029676-52d962fc-fc88-47d4-9401-7a03a3c70135.png)

**Comment by ashutoshverma-ct** [comment]
@aparveen @skrishn 

We checked the above geo-locator link, it is not accessible to us. So we checked the application and it is working without the geo-locator (screenshot attached) 

We also tried with our local geo-locators (secured, removed) but were unable to reproduce the exact case, at our side, the service does not return results from the particular service.

![image](https://user-images.githubusercontent.com/22743029/137124711-18570fa2-db82-4b1b-b6f9-e9489f801b20.png)

**Comment by sumitzarkar** [comment]
@skrishn  @aparveen 

Any updates on this ticket

**Comment by skrishn** [comment]
@sumitzarkar Please proceed with the solution you recommended. I don't want to wait any longer due to the shorter dev cycle we have. 
cc @aparveen

**Comment by sumitzarkar** [comment]
@aparveen 


### Root Cause
Here are the details of this issue:

- This issue is reproduced with the services which do not have singleLineAddresField name as 'SingleLine' and have Suggest capability. When the user clicks on the suggestion in the list this issue is reproduced.
- Currently, we are only able to reproduce this issue with the service (https://gis.whud.org/arcgis/rest/services/Public/SingleHouse/GeocodeServer)
- In this, we found that the singleLineAddressFieldName is different, it is '**Single Line Input**'
````
 "singleLineAddressField": {
  "name": "Single Line Input",
  "type": "esriFieldTypeString",
  "alias": "Full Address",
  "required": false,
  "length": 150
 }
````

- The application fetches the locations of selected suggestion candidates once the user clicks on them. Also, the application was assuming that the singleLineAddressField name should be 'SingleLine'

### Solution
- We have updated the code to fetch the address using the singleLineAddressFeild name defined in the service

**Comment by aparveen** [comment]
Verified in QA
