### ISSUE TITLE
BUG-000128224 Users are able to utilize the Search function in the CrowdSource Reporter solution, even after disabling the Search tool via the web app configuration.

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-reporter#522]
- Log into ArcGIS Online and go to your Content section
- Create an editable hosted feature layer and web map
     - Create > Feature Layer
- Create a new web application (Content > Create > Configurable Apps)
     - Search/Select the Crowdsource Reporter template > Create the application
- Go to your Groups in AGOL and create a new group that will be utilized for the application
     - Add the associated items (map/feature service) to the group
- Configure the application and go to the General section
     - Select the new Group that will be used for the application
- Go to the Search section, uncheck "Enable Search Tool"
     - Save the application and launch it in a new tab
- Click the Search icon and search for a city (Redlands, CA)
     - The Esri Word Geocoding Service is still being utilized for the search even though we disabled the Search tool during our configuration

**Comment by sumitzarkar** [comment]
@aparveen 

We analyzed this issue and here are our findings:
 - The Reporter app was designed to have the search widget always
 - Initially, App only use to honor the geocode services configured in the organization settings. And, if no geocoders in the org settings it fallbacks to ArcGIS World Geocoding service.
 - With the implementation of  #265 , We added the functionality to allow user to configure the geocoders to be used in the application.
 - When we checks the checkbox "Enable Search Tool" in the configuration we are not enableing / disabling the search but we are asking application to use the geocoders which are confugured here in the  application settings instead of using geocoders form the organization settings.
 - We think the "Enable Search Tool" text is making confusion and it should be updated to say "Use the below configured geocoder settings"

Current Implementation | After Updating Strings
-- | --
![image](https://user-images.githubusercontent.com/9443956/148499418-2ead7334-f896-4ae2-b99a-737594dae100.png)​ | ![image](https://user-images.githubusercontent.com/9443956/148498892-1aa39d40-828b-4291-a705-45b738cb1475.png)
 
- We think we should only update the strings in the configuration and should not do any changes to the functionality as CSR app was designed to have a search widget always. Also, if we change the behavior to show or hide the search the widget it would have backward compatibility issues and we need to do these changes in the Main map search and Search in Geoform.

Please let us know your thoughts on this.

**Comment by sumitzarkar** [comment]
@aparveen 

Please confirm if we should proceed wihth this string change 

![image](https://user-images.githubusercontent.com/9443956/148498892-1aa39d40-828b-4291-a705-45b738cb1475.png)

**Comment by aparveen** [comment]
@skrishn any suggestion on these strings?
![image](https://user-images.githubusercontent.com/10148401/150193974-8794c232-5e4f-4a32-9731-fc330a66a566.png)

**Comment by skrishn** [comment]
@sumitzarkar 
Please use the text below:

( Description section)
Configure the app with locator(s) from your organization to allow users to find location or data in the map, and optionally customize search properties for each locator.

(Text for the checkbox)
Enable to select locator(s)

cc @aparveen

**Comment by sumitzarkar** [comment]
@skrishn  @aparveen 

### Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

### Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | Yes
Have Runtime changes?​ | No
Impact on RTL | No
String Changes | Check for strings changes in the configuration panel

**Comment by aparveen** [comment]
Verified in qa
