### ISSUE TITLE
Reference Layer is not showing in the app

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-reporter#537]
User is having some trouble with getting reference layers to show up. she  configured it to show reference layers in the options tab within the app, it shows in the legend but will not draw. A link to the application  is below in case that helps.
App: https://gnrc.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=ca5d29c5a000423393a9c895aad18d89
Maps:
1) https://gnrc.maps.arcgis.com/apps/mapviewer/index.html?webmap=e77973abca25433a99e05c1908f6284a
 
2) https://gnrc.maps.arcgis.com/apps/mapviewer/index.html?webmap=c0f726b91409417c9d3c47ee30b25eb5
 
The congested by year and top crash areas are the reference layers and the map was created in new map viewer

**Comment by aparveen** [comment]
@sumitzarkar could you please look at this issue?

**Comment by sumitzarkar** [comment]
@aparveen 

We are analyzing this and will share our findings soon

**Comment by sumitzarkar** [comment]
@aparveen 

- We are able to reproduce this issue
- This is only reproducible only when webmap is created with the new map viewer  and has refrence layers
- We found the root cause for this and it is due to the layer.visibility property in new map viewer - Similar to #526 

## Dev Checklist

Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

## Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Runtime impact | 1. Test for Reference layers added as feature layer or a featureCollection layer  <br/> 2. Check for reference Layers in the GeoForm map which is shown only on mobile devices

**Comment by skrishn** [comment]
verified in qa
