### ISSUE TITLE
Crowdsource Reporter app failing to load

### ISSUE THREAD

**Issue by aparveen** [Esri/crowdsource-reporter#546]
Reported at the community page 
https://community.esri.com/t5/arcgis-solutions-questions/citizen-problem-reporter-hanging-on-submit-report/m-p/1300756#M1166
Chris was able to reproduce the issue with the following app and steps
**Test app**: https://www.arcgis.com/apps/CrowdsourceReporter/index.html?appid=d1c2bd8a608d4e2d9ef4b7e92aa66a90

It happens under a very specific use case, Here are the steps to replicate it:

1.	Deploy the CPR solution
2.	Open the Requests_reporter feature layer item details
3.	On the Settings tab change the editor setting  for ‘What features can editors see’ to ‘Editors can’t see any features, even those they add’ and click Save

![image](https://github.com/Esri/crowdsource-reporter/assets/10148401/bf7b5558-9ff2-43ca-ad93-8eb21f899f89)

 
5.	In your content share the Citizen Problem Reporter app and map, the Requests_reporter layer and Request Types csv with everyone
6.	Share the Citizen Problem Reporter group with everyone as well
7.	Open the Citizen Problem Reporter app in an incognito browser and on the splash screen enter as a guest
8.	The app will hand on loading

If you change the setting in step 3 back to ‘Editors can see all features’ this issue is no longer reproducible. I am not sure if something changed in feature services, but this is a valid setting for this workflow if you don’t want users to be able to query the service they are submitting to.

**Comment by aparveen** [comment]
@sumitzarkar could you please take a look at this at your earliest convenience? If we need to patch, we have until 23rd. I will be out of office from Thursday to next Monday, please reach out to Suba if you need anything
cc @skrishn

**Comment by skrishn** [comment]
@MikeTschudi Tested in QA ( Patch e). When I click on the newly added feature in the popup or add a comment I get this message. With guest login I can only see the features in regular window.
![MicrosoftTeams-image (7)](https://github.com/Esri/crowdsource-reporter/assets/3836616/9813e57a-d4e8-4d22-8e22-8f5fecb023e3)

The layer setting is probably causing this. When I switch it to other options (1 and 2), it doesnt throw the error.
![MicrosoftTeams-image (8)](https://github.com/Esri/crowdsource-reporter/assets/3836616/859ac4aa-5c76-4d29-a150-07d2134e76f8)

**Comment by MikeTschudi** [comment]
This is an expected error; we'll aim for a fix in the next release.

What happens is that this issue's error was occurring because a query failure broke the app; failure led to a Promise rejection and a console error.

When the "can't see any features" option is chosen, `query` is disabled and any attempts fail.

In order to get the app running for this release, the query failures are ignored and are handled the same as if the query returned no items.

A better approach is to query the feature service when the app starts to discover this option, and then to not even attempt a query if the option is set.  This will be more efficient and will not show the error messages.  It seemed too big a change at this point in the release, and so it was deferred.

**Comment by skrishn** [comment]
@MikeTschudi  Thank you for the quick response, and I agree with you.

**Comment by skrishn** [comment]
Closing the issue. Additional issue will be tracked and addressed on the issue #549
