### ISSUE TITLE
remove geographic filtering on list view

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#62]
Instead of filtering the list based on what is currently in the map view (which doesn't make sense in the mobile UI) and sorting it on most recent:

**When the user gives access to their current location** filter the list to features that are within a configurable distance of their location and sort with the nearest features first. This will add 2 parameters to the configuration panel:
- text entry of a number value
- drop-down selection of a unit (meters, kilometers, feet, miles)

After the list entry for the furthest feature in this buffer distance, provide an option to 'show more' (I'll send a UI comp of what this should look like as soon as I get if from the design team). This should list the features that are within 2x the buffer distance.

For example, if I've configured the app using a buffer distance of '500' and the unit 'feet', the list should open to show me the features that are within 500' of my current location. Clicking 'View More' should add to the list the features that are between 500' and 1000' of my current location.

**If the user's location is not available** load all the issues, sorted with the most recent at the top. Use OID to determine most recent feature.(should be current behavior)

Update the list and map:
- on map/layer selection
- report submission
- timed interval to bring in features submitted by other users. I am not sure what is appropriate/standard, so please suggest a value.

Do not update on pan/zoom.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : I have assigned this issue to you because the issue is larger than just the UI change. I will provide the comp/graphic for the button as soon as possible.

**Comment by allisonmuise** [comment]
Do no expand the buffer automatically if no features are found. Instead, display a message in the list are: 'No reports were found near you'
If location access was not given and no features are found the message should be: 'No reports were found'

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : In the phone call last week this question was raised: "Should only the listed features be displayed in the map?"

The answer to this is yes - only draw the features on the map that are currently included in the list.

**Comment by allisonmuise** [comment]
![loadmoream](https://cloud.githubusercontent.com/assets/2752195/6988513/fe162964-da06-11e4-9635-0dc02ba8f4ee.png)

Display 'Load More' after the last item within the current buffer distance. Unlike the 'Submit a Report' button text, this should be tied to the end of the list, not the bottom of the panel.

**Comment by allisonmuise** [comment]
This was moved to the backlog due to time constraints

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Few quick questions on implementing removal of geographic filtering:

1. App loads and features are displayed, sorted by distance from user's current location. Now, if user disables location access from smartphone settings, the app will continue to use the initial location, till user reloads the app. Is this ok?
2. The navigation controls also include a geolocation button. Clicking this will only zoom to user's current location and display a pushpin. 
 * This will have no effect on the features in list or map, i.e., it won't trigger buffering and re-sort features based on distance. 
 * If app loads without current location, the clicking geolocation will not trigger buffering and sorting.
 * Buffering and sorting will be triggered only on app load. Please confirm.
3. When app is loaded with access to geolocation and no features are found in initial buffer, we can display "No reports were found near you". However, the layer may contain reports that are quite far or just outside the initial buffer. In this case, the list and map will be empty and 'load more' button will not be displayed on the list. Hence, users have no way to explore features/reports in other areas. Please confirm if this is acceptable.
4. The same scenario above is applicable when user clicks 'load more', and the expanded buffer does not return features even though additional reports are present in other geographic areas. In this case, we will not automatically keep on expanding the buffer till we find features. The 'load more' will not be displayed anymore at this point. Is this correct?
4. Sorting the list by distance upon clicking 'load more'. Consider the below scenario:
  * load 1000 features initially (assuming 1000 is server limit)
  * display sorted by distance to user's current location
  * load additional 1000 features from either current or expanded buffer
  * re-sort all 2000 features by distance 
  * the list will scroll to top, it wont be possible to go back to same scroll position in the list because the list is redrawn and the order of features have also changed due to sorting by distance
  * user may lose track of the report he was looking at. Is this ok?
5. When more features are present in current buffer than can be returned at once by the service, the list that is displayed will not contain the 'true' nearest feature on top. There may be additional features in current buffer that were not returned by service. Those will be returned only when user clicks 'load more'. Initially, the feature on top of list will be the one that is nearest among the first 1000. However, when user clicks 'load more', the second batch of features might contain features that are nearer in the current buffer. Please confirm.

**Comment by allisonmuise** [comment]
First - Let's change 'Load more' to 'View more'. looking at this again, 'view' is a little less technical than 'load'

Second:
1. yes, this is ok
2. This is correct. I don't believe that the geolocation button will even work if the app is not allowed to access the user's location.
3. If the layer doesn't contain any features, 'view more' shouldn't display. If the layer contains more features than are currently loaded, view more should display.
4. As above + to avoid users having to click 'view more' multiple times without results, can 'view more' expand the buffer until results are found? I don't want this to happen automatically on app load because it could take a while, but I think this is ok as a user-initiated action, and preferable to several empty 'view more' clicks.
5. yes, this is ok.
6. yes, this is ok.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise Thank you very much for the quick response on this one.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Can you please provide us with some webmaps containing sample/representative data (point/line/polygon layers) that we can use for developing and testing this feature.

**Comment by allisonmuise** [comment]
verified
