### ISSUE TITLE
Configure link missing in Portal

### ISSUE THREAD

**Issue by phil7277** [Esri/crowdsource-reporter#73]
I deployed the application on to portal. Everything appears to function properly but options are missing. in the "item details " page, I do not have an option to "configure app". Utilizing portal 10.3.

**Comment by allisonmuise** [comment]
@phil7277 
It sounds like the item you created either:
A - Is a template (aka a configurable application item) rather than a fully configured app
To get a configure button:
1.	share this template with your group application templates group
2.	Open the group containing your reporter maps
3.	Share the group as an application
4.	Choose your reporter template to create a new web app item that will have a ‘configure button’

B - Contains errors in the item configuration
To find the error:
1.	Edit the template (not app) details
2.	Validate the contents of the Configuration Parameters section using a linter like http://jsonlint.com/
3.	Fix any errors, copy the corrected configuration into the Configuration Parameters section, and save.
4.	You will likely need to re-create any application built using this template.

**Comment by allisonmuise** [comment]
@phil7277 : closing this as we're now working with support to figure out what's going on.
