### ISSUE TITLE
36th character is cut off on the splash screen on Chrome and FF desktop browsers

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/crowdsource-reporter#78]
123456789123456789123456789123456789  - This is 36 Characters  

Image below illustrates the 36th character is cut off 

![screen shot 2015-05-07 at 11 58 06 am](https://cloud.githubusercontent.com/assets/2379312/7519785/6a631da2-f4b0-11e4-94f3-30a3ab7290b4.png)

Exists on Chrome and Firefox
Doesn't not occur IE9 OR Safari

**Comment by allisonmuise** [comment]
The exact number of characters that displays depends on what those characters are. For example, you can fit many more 1s than you can 2s because each 2 occupies more space than each 1. The difference between browsers is because of differences in how the browsers render the fonts. For my estimate of 36 chars I used an equal mix of wide and narrow letters.

I'm going to close this issue for now. We can reopen the size of this space if a specific subtitle needed for reverse compatibility doesn't fit. Otherwise this is just a known limitation.
