### ISSUE TITLE
The Cursor” floats on top of the submission form when scrolling

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/crowdsource-reporter#79]
Reporter on iPhone 6 (iOS 8.1.3) 
-go to report an issue
-Click on a text box 
-Scroll down
-You will see the the cursor floating on top of the form. 
-It will disappear once you stop

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Please investigate a fix for this. I am not seeing this behavior on any other form-entry web pages.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We will investigate and keep you updated on this issue.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas, @allisonmuise 

The issue seems to be known limitation of iOS devices, here are some reference links:

[https://bugs.webkit.org/show_bug.cgi?id=138201](https://bugs.webkit.org/show_bug.cgi?id=138201)

[https://github.com/twbs/bootstrap/issues/14708](https://github.com/twbs/bootstrap/issues/14708)

We are seeing this behavior in the polling app too.
This issue does not occur when the form is displayed as part of the main body itself. This issue occurs only when form is displayed in separate container other than the main body of the web page. In all our apps we always have at least two containers, one for the map and other for the form.

**Comment by allisonmuise** [comment]
Thanks for looking into this. closing the issue
