### ISSUE TITLE
Long text values should wrap in Details panel

### ISSUE THREAD

**Issue by allisonmuise** [Esri/crowdsource-reporter#96]
When a text value is longer than the details panel is wide, the text should wrap to the next line when it reaches the end of the panel. Currently the app displays a horizontal scroll bar.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise  @ScottOppmann  @LindsayThomas 

Popups usually contain field names and field values displayed in two columns. We are assuming that the text you are referring to is the field value which does not fit and hence displays horizontal scroll bar.  To fix this we are now wrapping at character level for field values, instead of word level .

For custom popups we are retaining wrapping at word level.
Please let us know if this is ok.

**Comment by allisonmuise** [comment]
You are correct - this only happens when there are no breaks in the text.
Please wrap at word level in all cases, as it will be rare that single words will exceed the provided space.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We had implemented wrapping at character level. We will now change this to wrapping at word level for all cases(field names, field values, custom popup).
For single words that exceeds the provided space, horizontal scroll bar will be displayed.

**Comment by allisonmuise** [comment]
yes, thanks!

**Comment by allisonmuise** [comment]
verified
